my:
 name: forezp
 age: 12

mybean:
 name: forezp
 age: 12
 number:  ${random.int}
 uuid : ${random.uuid}
 max: ${random.int(10)}
 value: ${random.value}
 greeting: hi,i'm  ${my.name}

#指定服务端口
server:
 port: 8082

spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sakila
  username: root
  password: 123456

jpa:
  hibernate:
   ddl-auto: update  # 第一次建表create  后面用update
  show-sql: true